bash <<'IMSGX'
#!/bin/bash
# ---------------------------------------------------------------------------
# EXTRACT IMESSAGE
# Generated by THE TOOL. Everything below runs on this machine and sends
# nothing anywhere. Read it before you run it — that is why it is readable.
# ---------------------------------------------------------------------------
set -euo pipefail

HOME_DIR='/Users/dan'
DB="$HOME_DIR/Library/Messages/chat.db"
DESK="$HOME_DIR/Desktop"
STAMP="$(date +%Y%m%d-%H%M%S)"
OUT="$DESK/imessage-5550104477-$STAMP.csv"
MANIFEST="$DESK/imessage-5550104477-$STAMP.manifest.txt"

say() { printf '%s\n' "$*"; }

say "EXTRACT IMESSAGE"
say "  database  $DB"
say "  output    $OUT"
say ""

# ---- 1. is it there at all ------------------------------------------------
if [ ! -f "$DB" ]; then
  say "No Messages database at:"
  say "  $DB"
  say ""
  say "Either this is the wrong home directory, or Messages has never been"
  say "signed in on this Mac. Check the short username with:  echo \$HOME"
  exit 1
fi

# ---- 2. Full Disk Access --------------------------------------------------
# This is the one thing the script cannot do for you: macOS will not let a
# process grant itself access to this file. So it is checked FIRST, rather
# than discovered as an empty result set after the query has "succeeded".
if ! /usr/bin/sqlite3 "$DB" 'SELECT 1;' >/dev/null 2>&1; then
  say "macOS is blocking access to the Messages database."
  say ""
  say "Grant Full Disk Access to whichever app this terminal is:"
  say "  System Settings > Privacy & Security > Full Disk Access"
  say "  turn ON the entry for Terminal (or iTerm, or your editor)"
  say "  then QUIT that app completely and open it again — the permission"
  say "  is only picked up on a fresh launch."
  say ""
  say "Opening that pane now. Re-run this command afterwards."
  open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles" 2>/dev/null || true
  exit 1
fi

# ---- 3. snapshot ----------------------------------------------------------
# Messages keeps recent traffic in a write-ahead log that has not been folded
# into the .db yet. Copying only chat.db drops it — the export comes back
# missing the last few days and looks complete. All three files travel
# together, and the query runs against the copy so a live Messages.app cannot
# change the data underneath it half way through.
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cp "$DB" "$WORK/chat.db"
if [ -f "$DB-wal" ]; then cp "$DB-wal" "$WORK/chat.db-wal"; fi
if [ -f "$DB-shm" ]; then cp "$DB-shm" "$WORK/chat.db-shm"; fi

# ---- 4. which decoder ------------------------------------------------------
# On Ventura and later most message text is not in the text column; it is in a
# binary blob, and getting it out properly needs byte-level parsing.
#
# /usr/bin/python3 on a Mac WITHOUT the developer tools is a stub that pops a
# GUI installer prompt when run — exactly the interruption this tool exists to
# avoid. So it is never run blind: a real python is looked for first, and the
# system one is only used when xcode-select confirms the tools are installed.
PY=""
for cand in /opt/homebrew/bin/python3 /usr/local/bin/python3; do
  if [ -x "$cand" ]; then PY="$cand"; break; fi
done
if [ -z "$PY" ] && /usr/bin/xcode-select -p >/dev/null 2>&1 && [ -x /usr/bin/python3 ]; then
  PY="/usr/bin/python3"
fi

RECOVERY="approximate (sqlite only)"
WROTE="unknown"

if [ -n "$PY" ]; then
  say "Reading, with full text recovery ($PY)…"
  /usr/bin/sqlite3 -csv -header "$WORK/chat.db" > "$WORK/raw.csv" <<'SQL_HEX'
SELECT
  m.ROWID AS row_id,
  COALESCE(m.guid, '') AS guid,
  datetime((CASE WHEN m.date > 1000000000000 THEN m.date / 1000000000 ELSE m.date END + 978307200), 'unixepoch', 'localtime') AS sent_at_local,
  datetime((CASE WHEN m.date > 1000000000000 THEN m.date / 1000000000 ELSE m.date END + 978307200), 'unixepoch') AS sent_at_utc,
  (CASE WHEN m.date > 1000000000000 THEN m.date / 1000000000 ELSE m.date END + 978307200) AS sent_epoch,
  CASE m.is_from_me WHEN 1 THEN 'SENT' ELSE 'RECEIVED' END AS direction,
  COALESCE(h.id, '') AS counterparty,
  '' AS contact_name,
  COALESCE(h.service, m.service, '') AS service,
  COALESCE(c.chat_identifier, '') AS chat_id,
  COALESCE(c.display_name, '') AS chat_name,
  CASE WHEN c.style = 43 THEN 1 ELSE 0 END AS is_group,
  COALESCE(m.cache_has_attachments, 0) AS has_attachment,
  COALESCE((
    SELECT group_concat(t.n, ' | ') FROM (
      SELECT a.transfer_name AS n
        FROM message_attachment_join maj
        JOIN attachment a ON a.ROWID = maj.attachment_id
       WHERE maj.message_id = m.ROWID
       ORDER BY a.ROWID
    ) t
  ), '') AS attachments,
  COALESCE(m.thread_originator_guid, '') AS reply_to_guid,
  COALESCE(m.associated_message_type, 0) AS tapback_type,
  COALESCE(m.associated_message_guid, '') AS tapback_on,
  COALESCE(m.is_read, 0) AS is_read,
  CASE
    WHEN m.date_read IS NULL OR m.date_read = 0 THEN ''
    ELSE datetime((CASE WHEN m.date_read > 1000000000000 THEN m.date_read / 1000000000 ELSE m.date_read END + 978307200), 'unixepoch', 'localtime')
  END AS read_at_local,
  COALESCE(m.text, '') AS text,
  CASE
    WHEN (m.text IS NULL OR m.text = '') AND m.attributedBody IS NOT NULL
    THEN hex(m.attributedBody)
    ELSE ''
  END AS body_hex
FROM message m
LEFT JOIN handle h ON h.ROWID = m.handle_id
-- One chat per message, chosen deterministically. A message in two chats would
-- otherwise come back twice; see trap 2 at the top of this file.
LEFT JOIN chat c ON c.ROWID = (
  SELECT min(j2.chat_id) FROM chat_message_join j2 WHERE j2.message_id = m.ROWID
)
WHERE (replace(replace(replace(replace(replace(replace(replace(h.id, '+', ''), '-', ''), ' ', ''), '(', ''), ')', ''), '.', ''), ' ', '') LIKE '%5550104477')
ORDER BY sent_epoch ASC, m.ROWID ASC;
SQL_HEX

  cat > "$WORK/decode.py" <<'PYSRC'
import csv, sys

# NSKeyedArchiver stores the string with a variable-width length prefix. See
# the note in body.ts: reading this as one byte truncates anything over 127
# bytes and mangles emoji, which is the failure that passes every casual test.
def _read_len(b, k):
    n = b[k]
    if n == 0x81:
        return int.from_bytes(b[k + 1:k + 3], 'little'), k + 3
    if n == 0x82:
        return int.from_bytes(b[k + 1:k + 5], 'little'), k + 5
    if n == 0x83:
        return int.from_bytes(b[k + 1:k + 9], 'little'), k + 9
    return n, k + 1

def decode(hexed):
    if not hexed:
        return None
    try:
        b = bytes.fromhex(hexed)
    except ValueError:
        return None
    # The class name can appear more than once in the archive's object table,
    # so every occurrence is tried and the first plausible one wins rather than
    # the first one found.
    for name in (b'NSString', b'NSMutableString'):
        at = -1
        while True:
            at = b.find(name, at + 1)
            if at < 0:
                break
            head = at + len(name)
            # The 0x2B marker follows within a short run of archiver bytes.
            # Bounded rather than open-ended: an unbounded search finds a '+'
            # inside the message text of some other field.
            mark = b.find(b'\x2b', head, head + 24)
            if mark < 0:
                continue
            n, start = _read_len(b, mark + 1)
            if n <= 0 or start + n > len(b):
                continue
            try:
                return b[start:start + n].decode('utf-8')
            except UnicodeDecodeError:
                # A length that decodes to nothing sensible is a length read at
                # the wrong offset. Try the next occurrence rather than
                # returning mojibake.
                continue
    return None

mode, src, dst = sys.argv[1], sys.argv[2], sys.argv[3]

with open(src, newline='', encoding='utf-8', errors='replace') as fh:
    rows = list(csv.reader(fh))

if not rows:
    sys.stderr.write('0 0 0\n')
    sys.exit(0)

head = rows[0]
i_text = head.index('text')
i_hex = head.index('body_hex')
keep = [i for i in range(len(head)) if i != i_hex]

recovered = 0
unrecovered = 0
for r in rows[1:]:
    if len(r) <= i_hex:
        continue
    if not r[i_text] and r[i_hex]:
        got = decode(r[i_hex])
        if got is None:
            unrecovered += 1
        else:
            r[i_text] = got
            recovered += 1

i_when = head.index('sent_at_local')
i_dir = head.index('direction')
i_who = head.index('counterparty')
i_name = head.index('contact_name')
i_svc = head.index('service')
i_chat = head.index('chat_name')
i_att = head.index('attachments')

with open(dst, 'w', newline='', encoding='utf-8') as out:
    if mode == 'csv':
        w = csv.writer(out, quoting=csv.QUOTE_MINIMAL)
        for r in rows:
            w.writerow([r[i] for i in keep] if len(r) > i_hex else r)
    else:
        for r in rows[1:]:
            if len(r) <= i_hex:
                continue
            who = r[i_name] or r[i_who] or 'unknown'
            if r[i_dir] == 'SENT':
                line = 'me -> ' + who
            else:
                line = who + ' -> me'
            tail = ' [' + r[i_svc] + ']' if r[i_svc] else ''
            if r[i_chat]:
                tail = ' [' + r[i_chat] + ']' + tail
            out.write(r[i_when] + '  ' + line + tail + '\n')
            body = r[i_text]
            if body:
                for ln in body.split('\n'):
                    out.write('    ' + ln + '\n')
            if r[i_att]:
                out.write('    <attachment: ' + r[i_att] + '>\n')
            out.write('\n')

sys.stderr.write('%d %d %d\n' % (len(rows) - 1, recovered, unrecovered))
PYSRC

  STATS="$("$PY" "$WORK/decode.py" 'csv' "$WORK/raw.csv" "$OUT" 2>&1 >/dev/null)"
  WROTE="$(printf '%s' "$STATS" | awk '{print $1}')"
  GOT="$(printf '%s' "$STATS" | awk '{print $2}')"
  MISSED="$(printf '%s' "$STATS" | awk '{print $3}')"
  RECOVERY="exact (byte-parsed; $GOT recovered from attributedBody, $MISSED not recoverable)"
else
  say "Reading. No python3 on this Mac, so text recovery is approximate…"
  /usr/bin/sqlite3 -csv -header "$WORK/chat.db" > "$OUT" <<'SQL_PLAIN'
SELECT
  m.ROWID AS row_id,
  COALESCE(m.guid, '') AS guid,
  datetime((CASE WHEN m.date > 1000000000000 THEN m.date / 1000000000 ELSE m.date END + 978307200), 'unixepoch', 'localtime') AS sent_at_local,
  datetime((CASE WHEN m.date > 1000000000000 THEN m.date / 1000000000 ELSE m.date END + 978307200), 'unixepoch') AS sent_at_utc,
  (CASE WHEN m.date > 1000000000000 THEN m.date / 1000000000 ELSE m.date END + 978307200) AS sent_epoch,
  CASE m.is_from_me WHEN 1 THEN 'SENT' ELSE 'RECEIVED' END AS direction,
  COALESCE(h.id, '') AS counterparty,
  '' AS contact_name,
  COALESCE(h.service, m.service, '') AS service,
  COALESCE(c.chat_identifier, '') AS chat_id,
  COALESCE(c.display_name, '') AS chat_name,
  CASE WHEN c.style = 43 THEN 1 ELSE 0 END AS is_group,
  COALESCE(m.cache_has_attachments, 0) AS has_attachment,
  COALESCE((
    SELECT group_concat(t.n, ' | ') FROM (
      SELECT a.transfer_name AS n
        FROM message_attachment_join maj
        JOIN attachment a ON a.ROWID = maj.attachment_id
       WHERE maj.message_id = m.ROWID
       ORDER BY a.ROWID
    ) t
  ), '') AS attachments,
  COALESCE(m.thread_originator_guid, '') AS reply_to_guid,
  COALESCE(m.associated_message_type, 0) AS tapback_type,
  COALESCE(m.associated_message_guid, '') AS tapback_on,
  COALESCE(m.is_read, 0) AS is_read,
  CASE
    WHEN m.date_read IS NULL OR m.date_read = 0 THEN ''
    ELSE datetime((CASE WHEN m.date_read > 1000000000000 THEN m.date_read / 1000000000 ELSE m.date_read END + 978307200), 'unixepoch', 'localtime')
  END AS read_at_local,
  COALESCE(NULLIF(m.text, ''), (
    SELECT
      CASE
        WHEN instr(body, 'NSDictionary') > 1 THEN substr(body, 1, instr(body, 'NSDictionary') - 1)
        WHEN instr(body, 'NSAttributeInfo') > 1 THEN substr(body, 1, instr(body, 'NSAttributeInfo') - 1)
        ELSE body
      END
    FROM (
      SELECT rtrim(ltrim(
        substr(
          CAST(m.attributedBody AS TEXT),
          instr(CAST(m.attributedBody AS TEXT), 'NSString') + 8
        ),
        char(1) || char(2) || char(3) || char(4) || char(5) || char(6) || char(7) ||
        char(8) || char(11) || char(12) || char(14) || char(15) || char(16) ||
        char(43) || char(129) || char(130) || char(132) || char(134) || char(148)
      ),
        char(1) || char(2) || char(6) || char(11) || char(12) || char(16) || char(134)
      ) AS body
    )
  ), '') AS text
FROM message m
LEFT JOIN handle h ON h.ROWID = m.handle_id
-- One chat per message, chosen deterministically. A message in two chats would
-- otherwise come back twice; see trap 2 at the top of this file.
LEFT JOIN chat c ON c.ROWID = (
  SELECT min(j2.chat_id) FROM chat_message_join j2 WHERE j2.message_id = m.ROWID
)
WHERE (replace(replace(replace(replace(replace(replace(replace(h.id, '+', ''), '-', ''), ' ', ''), '(', ''), ')', ''), '.', ''), ' ', '') LIKE '%5550104477')
ORDER BY sent_epoch ASC, m.ROWID ASC;
SQL_PLAIN
fi

# ---- 5. reconcile ----------------------------------------------------------
# A truncated export looks exactly like a complete one on disk. So the rows
# that were written are counted back and compared against what the same
# predicate says should be there, and a mismatch is a failure rather than a
# note. See CLAUDE.md section 3.
EXPECT="$(/usr/bin/sqlite3 "$WORK/chat.db" <<'SQL_COUNT'
SELECT count(*) FROM (SELECT m.ROWID
FROM message m
LEFT JOIN handle h ON h.ROWID = m.handle_id
-- One chat per message, chosen deterministically. A message in two chats would
-- otherwise come back twice; see trap 2 at the top of this file.
LEFT JOIN chat c ON c.ROWID = (
  SELECT min(j2.chat_id) FROM chat_message_join j2 WHERE j2.message_id = m.ROWID
)
WHERE (replace(replace(replace(replace(replace(replace(replace(h.id, '+', ''), '-', ''), ' ', ''), '(', ''), ')', ''), '.', ''), ' ', '') LIKE '%5550104477'));
SQL_COUNT
)"

if [ "$WROTE" = "unknown" ]; then
  # A CSV field may contain newlines, so records are counted by quote
  # parity rather than by line — counting lines would over-count any export
  # containing a multi-line message, which is most of them.
  WROTE="$(awk 'BEGIN{q=0;n=0} { c=gsub(/"/,"&"); q=(q+c)%2; if(q==0) n++ } END{print n-1}' "$OUT")"
fi

if [ "$WROTE" != "$EXPECT" ]; then
  say ""
  say "MISMATCH: the database has $EXPECT matching messages, but $WROTE were written."
  say "The export at $OUT is incomplete. Not opening it."
  exit 1
fi

# ---- 6. the manifest -------------------------------------------------------
# What was taken, and how. Beside the file rather than inside it, so the CSV
# stays a CSV that a spreadsheet will open.
{
  say "EXTRACT IMESSAGE — what this file is"
  say ""
  say "taken          $(date '+%Y-%m-%d %H:%M:%S %z')"
  say "from           $DB"
  say "messages       $WROTE"
  say "who            5550104477"
  say "scope          messages to and from that handle only"
  say "window         everything in the database"
  say "text recovery  $RECOVERY"
  say ""
  say "Timestamps are this Mac's local time. sent_epoch is seconds since 1970."
  say "Attachment FILES are not copied — only their names are recorded."
  say "Formatting, link previews and inline images are not recovered."
} > "$MANIFEST"

say ""
say "Done. $WROTE messages."
say "  $OUT"
say "  $MANIFEST"
open -R "$OUT" 2>/dev/null || true
IMSGX
