/**
 * The block the reader pastes.
 *
 * ---- why it is a heredoc and not one line ----------------------------------
 *
 * The promise is ONE PASTE, and a heredoc is one paste. It is not one line, and
 * the difference buys the things that make the command trustworthy: a Full Disk
 * Access preflight that tells you what to do instead of failing with sqlite's
 * error, a snapshot so a running Messages.app cannot hand back a half-written
 * database, two decoder paths chosen by what is actually on the machine, and a
 * reconciliation at the end that makes a truncated export loud. A single
 * semicolon-chained line can have the query and nothing else, which means every
 * one of those failures happens silently on somebody's Mac at midnight.
 *
 * The delimiter is quoted — `<<'IMSGX'` — so the shell that receives the paste
 * expands nothing inside it. Everything within arrives at bash verbatim, and
 * nothing the reader typed is interpreted on the way in. The nested heredocs
 * for the SQL and the python are quoted for the same reason.
 *
 * ---- the one thing it cannot do --------------------------------------------
 *
 * It cannot grant itself Full Disk Access. macOS will not allow that, and any
 * tool claiming otherwise is lying. So it checks first, and when the check
 * fails it opens the right pane of System Settings, says exactly which toggle
 * to flip, and exits non-zero — rather than running the query, getting an empty
 * result, and writing an empty file that looks like an answer.
 */

import { sh, heredoc, slug } from '../../shell/quote'
import { PY_DECODER } from './body'
import { buildQuery, buildCount } from './sql'
import type { QueryPlan } from './sql'
import { describeRange } from '../../shell/dates'

export type Format = 'csv' | 'txt'

export type ScriptPlan = QueryPlan & {
  format: Format
  /** `$HOME`, an absolute path, or a short username. Resolved below. */
  home: string
  /** Goes into the output filename. */
  label: string
}

/**
 * Resolve whatever was said about the home directory into a shell expression.
 *
 * Three shapes, because people say it three ways. `$HOME` is left as `$HOME`
 * and resolved by the reader's own shell, which is always right and is the
 * default. An absolute path is used as given. Anything else is taken as a short
 * username and becomes `/Users/<name>` — which is the case the question exists
 * for, since a reader generating this on a phone to run on a different Mac
 * cannot rely on `$HOME` being the right one.
 */
function homeExpr(raw: string): string {
  const value = raw.trim()
  if (!value || value === '$HOME' || value === '~') return '"$HOME"'
  if (value.startsWith('/')) return sh(value.replace(/\/+$/, ''))
  return sh(`/Users/${value.replace(/^\/+|\/+$/g, '')}`)
}

/**
 * Wrap the row query so sqlite formats a readable transcript itself.
 *
 * Only used on the path where there is no python3 — python does its own
 * formatting. Without this, asking for TXT on a machine with no python3 would
 * have to fall back to CSV, and a tool that silently gives you a different file
 * type than the one you asked for is worse than one that is a bit long.
 */
function txtWrapper(inner: string): string {
  const body = inner.replace(/;\s*$/, '')
  return `WITH rows AS (
${body}
)
SELECT
  sent_at_local || '  ' ||
  CASE direction
    WHEN 'SENT' THEN 'me -> ' || COALESCE(NULLIF(contact_name, ''), counterparty, 'unknown')
    ELSE COALESCE(NULLIF(contact_name, ''), counterparty, 'unknown') || ' -> me'
  END ||
  CASE WHEN chat_name <> '' THEN ' [' || chat_name || ']' ELSE '' END ||
  CASE WHEN service <> '' THEN ' [' || service || ']' ELSE '' END ||
  char(10) || '    ' || replace(COALESCE(text, ''), char(10), char(10) || '    ') ||
  CASE WHEN attachments <> '' THEN char(10) || '    <attachment: ' || attachments || '>' ELSE '' END
FROM rows;`
}

/** What the export is called, and what the reader is told it will be called. */
export const outputName = (plan: ScriptPlan) => `imessage-${slug(plan.label, 'export')}`

export function buildScript(plan: ScriptPlan): string {
  const home = homeExpr(plan.home)
  const name = outputName(plan)
  const ext = plan.format

  const withHex = buildQuery(plan, true)
  const plain = buildQuery(plan, false)
  const count = buildCount(plan)

  // The no-python path needs whichever shape the reader asked for; the python
  // path always takes the hex query, because python does the formatting.
  const plainOut = plan.format === 'txt' ? txtWrapper(plain) : plain

  const body = `#!/bin/bash
# ---------------------------------------------------------------------------
# EXTRACT IMESSAGE
# Generated by THE TOOL. Everything below runs on this machine and sends
# nothing anywhere. Read it before you run it — that is why it is readable.
# ---------------------------------------------------------------------------
set -euo pipefail

HOME_DIR=${home}
DB="$HOME_DIR/Library/Messages/chat.db"
DESK="$HOME_DIR/Desktop"
STAMP="$(date +%Y%m%d-%H%M%S)"
OUT="$DESK/${name}-$STAMP.${ext}"
MANIFEST="$DESK/${name}-$STAMP.manifest.txt"

say() { printf '%s\\n' "$*"; }

say "EXTRACT IMESSAGE"
say "  database  $DB"
say "  output    $OUT"
say ""

# ---- 1. is it there at all ------------------------------------------------
if [ ! -f "$DB" ]; then
  say "No Messages database at:"
  say "  $DB"
  say ""
  say "Either this is the wrong home directory, or Messages has never been"
  say "signed in on this Mac. Check the short username with:  echo \\$HOME"
  exit 1
fi

# ---- 2. Full Disk Access --------------------------------------------------
# This is the one thing the script cannot do for you: macOS will not let a
# process grant itself access to this file. So it is checked FIRST, rather
# than discovered as an empty result set after the query has "succeeded".
if ! /usr/bin/sqlite3 "$DB" 'SELECT 1;' >/dev/null 2>&1; then
  say "macOS is blocking access to the Messages database."
  say ""
  say "Grant Full Disk Access to whichever app this terminal is:"
  say "  System Settings > Privacy & Security > Full Disk Access"
  say "  turn ON the entry for Terminal (or iTerm, or your editor)"
  say "  then QUIT that app completely and open it again — the permission"
  say "  is only picked up on a fresh launch."
  say ""
  say "Opening that pane now. Re-run this command afterwards."
  open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles" 2>/dev/null || true
  exit 1
fi

# ---- 3. snapshot ----------------------------------------------------------
# Messages keeps recent traffic in a write-ahead log that has not been folded
# into the .db yet. Copying only chat.db drops it — the export comes back
# missing the last few days and looks complete. All three files travel
# together, and the query runs against the copy so a live Messages.app cannot
# change the data underneath it half way through.
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cp "$DB" "$WORK/chat.db"
if [ -f "$DB-wal" ]; then cp "$DB-wal" "$WORK/chat.db-wal"; fi
if [ -f "$DB-shm" ]; then cp "$DB-shm" "$WORK/chat.db-shm"; fi

# ---- 4. which decoder ------------------------------------------------------
# On Ventura and later most message text is not in the text column; it is in a
# binary blob, and getting it out properly needs byte-level parsing.
#
# /usr/bin/python3 on a Mac WITHOUT the developer tools is a stub that pops a
# GUI installer prompt when run — exactly the interruption this tool exists to
# avoid. So it is never run blind: a real python is looked for first, and the
# system one is only used when xcode-select confirms the tools are installed.
PY=""
for cand in /opt/homebrew/bin/python3 /usr/local/bin/python3; do
  if [ -x "$cand" ]; then PY="$cand"; break; fi
done
if [ -z "$PY" ] && /usr/bin/xcode-select -p >/dev/null 2>&1 && [ -x /usr/bin/python3 ]; then
  PY="/usr/bin/python3"
fi

RECOVERY="approximate (sqlite only)"
WROTE="unknown"

if [ -n "$PY" ]; then
  say "Reading, with full text recovery ($PY)…"
  /usr/bin/sqlite3 -csv -header "$WORK/chat.db" > "$WORK/raw.csv" ${heredoc('SQL_HEX', withHex)}

  cat > "$WORK/decode.py" ${heredoc('PYSRC', PY_DECODER)}

  STATS="$("$PY" "$WORK/decode.py" ${sh(plan.format)} "$WORK/raw.csv" "$OUT" 2>&1 >/dev/null)"
  WROTE="$(printf '%s' "$STATS" | awk '{print $1}')"
  GOT="$(printf '%s' "$STATS" | awk '{print $2}')"
  MISSED="$(printf '%s' "$STATS" | awk '{print $3}')"
  RECOVERY="exact (byte-parsed; $GOT recovered from attributedBody, $MISSED not recoverable)"
else
  say "Reading. No python3 on this Mac, so text recovery is approximate…"
  /usr/bin/sqlite3 -csv -header "$WORK/chat.db" > "$OUT" ${heredoc('SQL_PLAIN', plainOut)}
fi

# ---- 5. reconcile ----------------------------------------------------------
# A truncated export looks exactly like a complete one on disk. So the rows
# that were written are counted back and compared against what the same
# predicate says should be there, and a mismatch is a failure rather than a
# note. See CLAUDE.md section 3.
EXPECT="$(/usr/bin/sqlite3 "$WORK/chat.db" ${heredoc('SQL_COUNT', count)}
)"

if [ "$WROTE" = "unknown" ]; then
${
  plan.format === 'csv'
    ? `  # A CSV field may contain newlines, so records are counted by quote
  # parity rather than by line — counting lines would over-count any export
  # containing a multi-line message, which is most of them.
  WROTE="$(awk 'BEGIN{q=0;n=0} { c=gsub(/"/,"&"); q=(q+c)%2; if(q==0) n++ } END{print n-1}' "$OUT")"`
    : `  # Every record opens at column 0 with its timestamp; message body lines
  # are indented four spaces, so this cannot count a message's own text.
  WROTE="$(grep -c '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] ' "$OUT" || true)"`
}
fi

if [ "$WROTE" != "$EXPECT" ]; then
  say ""
  say "MISMATCH: the database has $EXPECT matching messages, but $WROTE were written."
  say "The export at $OUT is incomplete. Not opening it."
  exit 1
fi

# ---- 6. the manifest -------------------------------------------------------
# What was taken, and how. Beside the file rather than inside it, so the CSV
# stays a CSV that a spreadsheet will open.
{
  say "EXTRACT IMESSAGE — what this file is"
  say ""
  say "taken          $(date '+%Y-%m-%d %H:%M:%S %z')"
  say "from           $DB"
  say "messages       $WROTE"
  say "who            ${plan.targets.length ? plan.targets.map((t) => t.name ? `${t.name} <${t.handle}>` : t.handle).join(', ').replace(/"/g, "'") : 'everybody in the database'}"
  say "scope          ${plan.scope === 'conversation' ? 'whole conversations, including group threads' : 'messages to and from that handle only'}"
  say "window         ${describeRange(plan.range)}"
  say "text recovery  $RECOVERY"
  say ""
  say "Timestamps are this Mac's local time. sent_epoch is seconds since 1970."
  say "Attachment FILES are not copied — only their names are recorded."
  say "Formatting, link previews and inline images are not recovered."
} > "$MANIFEST"

say ""
say "Done. $WROTE messages."
say "  $OUT"
say "  $MANIFEST"
open -R "$OUT" 2>/dev/null || true
`

  return `bash ${heredoc('IMSGX', body.trim())}`
}
